// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAo-3NqB_sWRmlkLFTwcphlADEQSpOoNc',
    appId: '1:961127477456:web:05306d7aff38f86459eed5',
    messagingSenderId: '961127477456',
    projectId: 'intensiv-7750c',
    authDomain: 'intensiv-7750c.firebaseapp.com',
    storageBucket: 'intensiv-7750c.appspot.com',
    measurementId: 'G-X7RGRG0H2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AFkQ5A3rvEyQiZuA_eAmp9xURhA-PRw',
    appId: '1:961127477456:android:79c4979262b6b16159eed5',
    messagingSenderId: '961127477456',
    projectId: 'intensiv-7750c',
    storageBucket: 'intensiv-7750c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcUqbvtZ4VJcUnRhHcpV2CxLZFLrCbK-E',
    appId: '1:961127477456:ios:a440cf525853696959eed5',
    messagingSenderId: '961127477456',
    projectId: 'intensiv-7750c',
    storageBucket: 'intensiv-7750c.appspot.com',
    iosBundleId: 'com.example.intensivWise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcUqbvtZ4VJcUnRhHcpV2CxLZFLrCbK-E',
    appId: '1:961127477456:ios:a440cf525853696959eed5',
    messagingSenderId: '961127477456',
    projectId: 'intensiv-7750c',
    storageBucket: 'intensiv-7750c.appspot.com',
    iosBundleId: 'com.example.intensivWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAo-3NqB_sWRmlkLFTwcphlADEQSpOoNc',
    appId: '1:961127477456:web:7272220f2d996e1e59eed5',
    messagingSenderId: '961127477456',
    projectId: 'intensiv-7750c',
    authDomain: 'intensiv-7750c.firebaseapp.com',
    storageBucket: 'intensiv-7750c.appspot.com',
    measurementId: 'G-S3PJQXFRZ3',
  );
}
